name: Sync Crowdin

on:
  push:
    branches:
      - 'main'
    paths:
      - 'base/bunny.json'
      - '.github/workflows/crowdin.yml'
  schedule:
    - cron: "0 17 * * 6" # "At 17:00 on Saturday."
  workflow_dispatch:
  
jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crowdin
        uses: crowdin/github-action@1.4.11
        with:
          config: crowdin.yml
          upload_sources: true
          upload_translations: true
          download_translations: true
          push_translations: true
          create_pull_request: false
          localization_branch_name: crowdin
          commit_message: 'sync translations'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Merge
        run: |
          sudo chmod -R ugo+rwX .
          git checkout main
          git add *
          git merge crowdin
          git push